version: "3"

env:
  NATS_PORT: 4222
  STATIC_DIR: "web/static"
  ORISUN_LOGGING_LEVEL: INFO
  ORISUN_PG_PASSWORD: "password@1"

tasks:
  tools:
    cmds:
      - go install github.com/a-h/templ/cmd/templ@v0.3.857
      - go install github.com/air-verse/air@latest
      - go install github.com/go-delve/delve/cmd/dlv@v1.24.1
      - go install github.com/go-task/task/v3/cmd/task@latest

  # The `build:` tasks below are used together for production builds of a project
  build:templ:
    cmds:
      - templ generate
    sources:
      - "**/*.templ"
    generates:
      - "**/*_templ.go"

  build:styles:
    cmds:
      - pnpm exec tailwindcss -c tailwind.config.js -i web/styles/styles.css -o $STATIC_DIR/index.css
    sources:
      - "./web/**/*.html"
      - "./web/**/*.ts"
      - "./web/**/*.templ"
      - "./web/**/*.go"
    generates:
      - "{{.STATIC_DIR}}/index.js"

  build:esbuild:
    cmds:
      - pnpm exec esbuild web/libs/datastar/index.ts --bundle --outdir=$STATIC_DIR
    sources:
      - "web/libs/datastar/index.ts"
    generates:
      - "{{.STATIC_DIR}}/index.js"

  build:lit-html:
    cmds:
      - pnpm -r --filter=lit-html build
    sources:
      - "web/libs/lit-html/src/**/*.ts"
    generates:
      - "{{.STATIC_DIR}}/lit-html*"

  build:
    cmds:
      - go build -o bin/main .
    deps:
      - build:lit-html
      - build:templ
      - build:esbuild
      - build:styles

  # Use this task to debug with the delve debugger
  debug:
    cmds:
      - dlv exec ./bin/main
    deps:
      - build

  # The `live:` tasks below are used together for development builds and will live-reload the entire project
  live:templ:
    cmds:
      - templ generate --watch --proxy="http://localhost:8080" --open-browser=false

  live:styles:
    cmds:
      - pnpm exec tailwindcss -c tailwind.config.js -i web/styles/styles.css -o $STATIC_DIR/index.css --watch

  live:esbuild:
    cmds:
      - pnpm exec esbuild web/libs/datastar/index.ts --sourcemap --bundle --outdir=$STATIC_DIR --watch

  live:lit-html:
    cmds:
      - pnpm -r --filter=lit-html build:dev

  live:server:
    cmds:
      - |
        air  \
         -build.cmd "go build -tags dev -o tmp/bin/main" \
         -build.bin "tmp/bin/main" \
         -build.delay "100" \
         -build.exclude_dir "data,node_modules,web/libs/datastar/node_modules,web/libs/lit-html/node_modules" \
         -build.include_ext "go" \
         -build.stop_on_error "false" \
         -build.send_interrupt "true" \
         -build.kill_delay "200" \
         -misc.clean_on_exit "true"

  live:reload:
    cmds:
      - |
        air \
        -build.cmd "templ generate --notify-proxy" \
        -build.bin "true" \
        -build.delay "300" \
        -build.exclude_dir "" \
        -build.include_dir "$STATIC_DIR" \
        -build.include_ext "js,css" \
        -build.send_interrupt "true" \
        -build.kill_delay "200"

  live:
    deps:
      - live:templ
      # - live:styles
      # - live:lit-html
      # - live:esbuild
      - live:server
      - live:reload

  run:
    cmds:
      - ./bin/main
    deps:
      - build