// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// import "orisun/src/orisun/admin/templates/layout"
func AddUser(currentPath string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<sl-dialog id=\"add-user-dialog\" label=\"Create New User\" class=\"dialog-overview\" data-signals=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(`{ username: '' ,
    password: '' , role: '' }`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `admin/templates/add-user.templ`, Line: 8, Col: 30}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" data-on-load=\"document.querySelector(&#39;#add-user-dialog&#39;).show()\"><div><div class=\"space-y-4\"><sl-input label=\"Username\" required clearable data-bind-username><sl-icon slot=\"prefix\" name=\"person\"></sl-icon></sl-input> <sl-input type=\"password\" label=\"Password\" required password-toggle data-bind-password><sl-icon slot=\"prefix\" name=\"key\"></sl-icon></sl-input> <sl-select label=\"Roles\" clearable help-text=\"Select one or more roles\" data-bind-role><sl-icon slot=\"prefix\" name=\"shield\"></sl-icon> <sl-option value=\"admin\">Admin</sl-option> <sl-option value=\"user\">User</sl-option></sl-select></div><div slot=\"footer\" class=\"flex justify-end gap-2\"><sl-button data-on-click=\"document.querySelector(&#39;#add-user-dialog&#39;).hide()\"><sl-icon slot=\"prefix\" name=\"x-circle\"></sl-icon> Cancel</sl-button> <sl-button variant=\"primary\" data-on-click=\"@post(&#39;/admin/users&#39;)\"><sl-icon slot=\"prefix\" name=\"check2-circle\"></sl-icon> Create User</sl-button></div></div></sl-dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
