// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: admin.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoundaryLifecycleStatus int32

const (
	BoundaryLifecycleStatus_BOUNDARY_LIFECYCLE_STATUS_UNSPECIFIED  BoundaryLifecycleStatus = 0
	BoundaryLifecycleStatus_BOUNDARY_LIFECYCLE_STATUS_PROVISIONING BoundaryLifecycleStatus = 1
	BoundaryLifecycleStatus_BOUNDARY_LIFECYCLE_STATUS_ACTIVE       BoundaryLifecycleStatus = 2
	BoundaryLifecycleStatus_BOUNDARY_LIFECYCLE_STATUS_FAILED       BoundaryLifecycleStatus = 3
)

// Enum value maps for BoundaryLifecycleStatus.
var (
	BoundaryLifecycleStatus_name = map[int32]string{
		0: "BOUNDARY_LIFECYCLE_STATUS_UNSPECIFIED",
		1: "BOUNDARY_LIFECYCLE_STATUS_PROVISIONING",
		2: "BOUNDARY_LIFECYCLE_STATUS_ACTIVE",
		3: "BOUNDARY_LIFECYCLE_STATUS_FAILED",
	}
	BoundaryLifecycleStatus_value = map[string]int32{
		"BOUNDARY_LIFECYCLE_STATUS_UNSPECIFIED":  0,
		"BOUNDARY_LIFECYCLE_STATUS_PROVISIONING": 1,
		"BOUNDARY_LIFECYCLE_STATUS_ACTIVE":       2,
		"BOUNDARY_LIFECYCLE_STATUS_FAILED":       3,
	}
)

func (x BoundaryLifecycleStatus) Enum() *BoundaryLifecycleStatus {
	p := new(BoundaryLifecycleStatus)
	*p = x
	return p
}

func (x BoundaryLifecycleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BoundaryLifecycleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_proto_enumTypes[0].Descriptor()
}

func (BoundaryLifecycleStatus) Type() protoreflect.EnumType {
	return &file_admin_proto_enumTypes[0]
}

func (x BoundaryLifecycleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BoundaryLifecycleStatus.Descriptor instead.
func (BoundaryLifecycleStatus) EnumDescriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

// AdminUser represents a user in the system
type AdminUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUser) Reset() {
	*x = AdminUser{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUser) ProtoMessage() {}

func (x *AdminUser) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUser.ProtoReflect.Descriptor instead.
func (*AdminUser) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdminUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminUser) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *AdminUser) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AdminUser) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateUserRequest creates a new user
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

// CreateUserResponse returns the created user
type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *AdminUser             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserResponse) GetUser() *AdminUser {
	if x != nil {
		return x.User
	}
	return nil
}

// DeleteUserRequest deletes a user by ID
type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// DeleteUserResponse indicates success
type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ChangePasswordRequest changes a user's password
type ChangePasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrentPassword string                 `protobuf:"bytes,2,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ChangePasswordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangePasswordRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// ChangePasswordResponse indicates success
type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ChangePasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ListUsersRequest lists all users
type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{7}
}

// ListUsersResponse returns list of users
type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*AdminUser           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ListUsersResponse) GetUsers() []*AdminUser {
	if x != nil {
		return x.Users
	}
	return nil
}

// ValidateCredentialsRequest validates username/password
type ValidateCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCredentialsRequest) Reset() {
	*x = ValidateCredentialsRequest{}
	mi := &file_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCredentialsRequest) ProtoMessage() {}

func (x *ValidateCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCredentialsRequest.ProtoReflect.Descriptor instead.
func (*ValidateCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateCredentialsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ValidateCredentialsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// ValidateCredentialsResponse returns validation result
type ValidateCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	User          *AdminUser             `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCredentialsResponse) Reset() {
	*x = ValidateCredentialsResponse{}
	mi := &file_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCredentialsResponse) ProtoMessage() {}

func (x *ValidateCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCredentialsResponse.ProtoReflect.Descriptor instead.
func (*ValidateCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateCredentialsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ValidateCredentialsResponse) GetUser() *AdminUser {
	if x != nil {
		return x.User
	}
	return nil
}

// GetUserCountRequest gets total user count
type GetUserCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCountRequest) Reset() {
	*x = GetUserCountRequest{}
	mi := &file_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCountRequest) ProtoMessage() {}

func (x *GetUserCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCountRequest.ProtoReflect.Descriptor instead.
func (*GetUserCountRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{11}
}

// GetUserCountResponse returns user count
type GetUserCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCountResponse) Reset() {
	*x = GetUserCountResponse{}
	mi := &file_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCountResponse) ProtoMessage() {}

func (x *GetUserCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCountResponse.ProtoReflect.Descriptor instead.
func (*GetUserCountResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GetEventCountRequest gets event count for a boundary
type GetEventCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boundary      string                 `protobuf:"bytes,1,opt,name=boundary,proto3" json:"boundary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventCountRequest) Reset() {
	*x = GetEventCountRequest{}
	mi := &file_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventCountRequest) ProtoMessage() {}

func (x *GetEventCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventCountRequest.ProtoReflect.Descriptor instead.
func (*GetEventCountRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{13}
}

func (x *GetEventCountRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

// GetEventCountResponse returns event count
type GetEventCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventCountResponse) Reset() {
	*x = GetEventCountResponse{}
	mi := &file_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventCountResponse) ProtoMessage() {}

func (x *GetEventCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventCountResponse.ProtoReflect.Descriptor instead.
func (*GetEventCountResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{14}
}

func (x *GetEventCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// BoundaryPlacementInput selects the durable backend and its physical
// namespace (a PostgreSQL schema or SQLite database namespace).
type BoundaryPlacementInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backend       string                 `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundaryPlacementInput) Reset() {
	*x = BoundaryPlacementInput{}
	mi := &file_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundaryPlacementInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundaryPlacementInput) ProtoMessage() {}

func (x *BoundaryPlacementInput) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundaryPlacementInput.ProtoReflect.Descriptor instead.
func (*BoundaryPlacementInput) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{15}
}

func (x *BoundaryPlacementInput) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *BoundaryPlacementInput) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type BoundaryInfo struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	Name                 string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Placement            *BoundaryPlacementInput `protobuf:"bytes,3,opt,name=placement,proto3" json:"placement,omitempty"`
	Status               BoundaryLifecycleStatus `protobuf:"varint,4,opt,name=status,proto3,enum=orisun.BoundaryLifecycleStatus" json:"status,omitempty"`
	ExistedBeforeCatalog bool                    `protobuf:"varint,5,opt,name=existed_before_catalog,json=existedBeforeCatalog,proto3" json:"existed_before_catalog,omitempty"`
	LastError            string                  `protobuf:"bytes,6,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	DefinitionPosition   *Position               `protobuf:"bytes,7,opt,name=definition_position,json=definitionPosition,proto3" json:"definition_position,omitempty"`
	StatusPosition       *Position               `protobuf:"bytes,8,opt,name=status_position,json=statusPosition,proto3" json:"status_position,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BoundaryInfo) Reset() {
	*x = BoundaryInfo{}
	mi := &file_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundaryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundaryInfo) ProtoMessage() {}

func (x *BoundaryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundaryInfo.ProtoReflect.Descriptor instead.
func (*BoundaryInfo) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{16}
}

func (x *BoundaryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoundaryInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BoundaryInfo) GetPlacement() *BoundaryPlacementInput {
	if x != nil {
		return x.Placement
	}
	return nil
}

func (x *BoundaryInfo) GetStatus() BoundaryLifecycleStatus {
	if x != nil {
		return x.Status
	}
	return BoundaryLifecycleStatus_BOUNDARY_LIFECYCLE_STATUS_UNSPECIFIED
}

func (x *BoundaryInfo) GetExistedBeforeCatalog() bool {
	if x != nil {
		return x.ExistedBeforeCatalog
	}
	return false
}

func (x *BoundaryInfo) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *BoundaryInfo) GetDefinitionPosition() *Position {
	if x != nil {
		return x.DefinitionPosition
	}
	return nil
}

func (x *BoundaryInfo) GetStatusPosition() *Position {
	if x != nil {
		return x.StatusPosition
	}
	return nil
}

type CreateBoundaryRequest struct {
	state       protoimpl.MessageState  `protogen:"open.v1"`
	Name        string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Placement   *BoundaryPlacementInput `protobuf:"bytes,3,opt,name=placement,proto3" json:"placement,omitempty"`
	// Set when adopting physical storage that predates the catalog definition.
	ExistedBeforeCatalog bool `protobuf:"varint,4,opt,name=existed_before_catalog,json=existedBeforeCatalog,proto3" json:"existed_before_catalog,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateBoundaryRequest) Reset() {
	*x = CreateBoundaryRequest{}
	mi := &file_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoundaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoundaryRequest) ProtoMessage() {}

func (x *CreateBoundaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoundaryRequest.ProtoReflect.Descriptor instead.
func (*CreateBoundaryRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{17}
}

func (x *CreateBoundaryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBoundaryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBoundaryRequest) GetPlacement() *BoundaryPlacementInput {
	if x != nil {
		return x.Placement
	}
	return nil
}

func (x *CreateBoundaryRequest) GetExistedBeforeCatalog() bool {
	if x != nil {
		return x.ExistedBeforeCatalog
	}
	return false
}

type CreateBoundaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boundary      *BoundaryInfo          `protobuf:"bytes,1,opt,name=boundary,proto3" json:"boundary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoundaryResponse) Reset() {
	*x = CreateBoundaryResponse{}
	mi := &file_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoundaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoundaryResponse) ProtoMessage() {}

func (x *CreateBoundaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoundaryResponse.ProtoReflect.Descriptor instead.
func (*CreateBoundaryResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{18}
}

func (x *CreateBoundaryResponse) GetBoundary() *BoundaryInfo {
	if x != nil {
		return x.Boundary
	}
	return nil
}

type ListBoundariesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBoundariesRequest) Reset() {
	*x = ListBoundariesRequest{}
	mi := &file_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBoundariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBoundariesRequest) ProtoMessage() {}

func (x *ListBoundariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBoundariesRequest.ProtoReflect.Descriptor instead.
func (*ListBoundariesRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{19}
}

type ListBoundariesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boundaries    []*BoundaryInfo        `protobuf:"bytes,1,rep,name=boundaries,proto3" json:"boundaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBoundariesResponse) Reset() {
	*x = ListBoundariesResponse{}
	mi := &file_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBoundariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBoundariesResponse) ProtoMessage() {}

func (x *ListBoundariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBoundariesResponse.ProtoReflect.Descriptor instead.
func (*ListBoundariesResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{20}
}

func (x *ListBoundariesResponse) GetBoundaries() []*BoundaryInfo {
	if x != nil {
		return x.Boundaries
	}
	return nil
}

type GetBoundaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoundaryRequest) Reset() {
	*x = GetBoundaryRequest{}
	mi := &file_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoundaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoundaryRequest) ProtoMessage() {}

func (x *GetBoundaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoundaryRequest.ProtoReflect.Descriptor instead.
func (*GetBoundaryRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{21}
}

func (x *GetBoundaryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetBoundaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boundary      *BoundaryInfo          `protobuf:"bytes,1,opt,name=boundary,proto3" json:"boundary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoundaryResponse) Reset() {
	*x = GetBoundaryResponse{}
	mi := &file_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoundaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoundaryResponse) ProtoMessage() {}

func (x *GetBoundaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoundaryResponse.ProtoReflect.Descriptor instead.
func (*GetBoundaryResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{22}
}

func (x *GetBoundaryResponse) GetBoundary() *BoundaryInfo {
	if x != nil {
		return x.Boundary
	}
	return nil
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\x06orisun\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x10eventstore.proto\"\xe0\x01\n" +
	"\tAdminUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"u\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\";\n" +
	"\x12CreateUserResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.orisun.AdminUserR\x04user\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"~\n" +
	"\x15ChangePasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x10current_password\x18\x02 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"2\n" +
	"\x16ChangePasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x12\n" +
	"\x10ListUsersRequest\"<\n" +
	"\x11ListUsersResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.orisun.AdminUserR\x05users\"T\n" +
	"\x1aValidateCredentialsRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"^\n" +
	"\x1bValidateCredentialsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x04user\x18\x02 \x01(\v2\x11.orisun.AdminUserR\x04user\"\x15\n" +
	"\x13GetUserCountRequest\",\n" +
	"\x14GetUserCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"2\n" +
	"\x14GetEventCountRequest\x12\x1a\n" +
	"\bboundary\x18\x01 \x01(\tR\bboundary\"-\n" +
	"\x15GetEventCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"P\n" +
	"\x16BoundaryPlacementInput\x12\x18\n" +
	"\abackend\x18\x01 \x01(\tR\abackend\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"\x8e\x03\n" +
	"\fBoundaryInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12<\n" +
	"\tplacement\x18\x03 \x01(\v2\x1e.orisun.BoundaryPlacementInputR\tplacement\x127\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1f.orisun.BoundaryLifecycleStatusR\x06status\x124\n" +
	"\x16existed_before_catalog\x18\x05 \x01(\bR\x14existedBeforeCatalog\x12\x1d\n" +
	"\n" +
	"last_error\x18\x06 \x01(\tR\tlastError\x12A\n" +
	"\x13definition_position\x18\a \x01(\v2\x10.orisun.PositionR\x12definitionPosition\x129\n" +
	"\x0fstatus_position\x18\b \x01(\v2\x10.orisun.PositionR\x0estatusPosition\"\xc1\x01\n" +
	"\x15CreateBoundaryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12<\n" +
	"\tplacement\x18\x03 \x01(\v2\x1e.orisun.BoundaryPlacementInputR\tplacement\x124\n" +
	"\x16existed_before_catalog\x18\x04 \x01(\bR\x14existedBeforeCatalog\"J\n" +
	"\x16CreateBoundaryResponse\x120\n" +
	"\bboundary\x18\x01 \x01(\v2\x14.orisun.BoundaryInfoR\bboundary\"\x17\n" +
	"\x15ListBoundariesRequest\"N\n" +
	"\x16ListBoundariesResponse\x124\n" +
	"\n" +
	"boundaries\x18\x01 \x03(\v2\x14.orisun.BoundaryInfoR\n" +
	"boundaries\"(\n" +
	"\x12GetBoundaryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"G\n" +
	"\x13GetBoundaryResponse\x120\n" +
	"\bboundary\x18\x01 \x01(\v2\x14.orisun.BoundaryInfoR\bboundary*\xbc\x01\n" +
	"\x17BoundaryLifecycleStatus\x12)\n" +
	"%BOUNDARY_LIFECYCLE_STATUS_UNSPECIFIED\x10\x00\x12*\n" +
	"&BOUNDARY_LIFECYCLE_STATUS_PROVISIONING\x10\x01\x12$\n" +
	" BOUNDARY_LIFECYCLE_STATUS_ACTIVE\x10\x02\x12$\n" +
	" BOUNDARY_LIFECYCLE_STATUS_FAILED\x10\x032\x87\x06\n" +
	"\x05Admin\x12O\n" +
	"\x0eCreateBoundary\x12\x1d.orisun.CreateBoundaryRequest\x1a\x1e.orisun.CreateBoundaryResponse\x12O\n" +
	"\x0eListBoundaries\x12\x1d.orisun.ListBoundariesRequest\x1a\x1e.orisun.ListBoundariesResponse\x12F\n" +
	"\vGetBoundary\x12\x1a.orisun.GetBoundaryRequest\x1a\x1b.orisun.GetBoundaryResponse\x12C\n" +
	"\n" +
	"CreateUser\x12\x19.orisun.CreateUserRequest\x1a\x1a.orisun.CreateUserResponse\x12C\n" +
	"\n" +
	"DeleteUser\x12\x19.orisun.DeleteUserRequest\x1a\x1a.orisun.DeleteUserResponse\x12O\n" +
	"\x0eChangePassword\x12\x1d.orisun.ChangePasswordRequest\x1a\x1e.orisun.ChangePasswordResponse\x12@\n" +
	"\tListUsers\x12\x18.orisun.ListUsersRequest\x1a\x19.orisun.ListUsersResponse\x12^\n" +
	"\x13ValidateCredentials\x12\".orisun.ValidateCredentialsRequest\x1a#.orisun.ValidateCredentialsResponse\x12I\n" +
	"\fGetUserCount\x12\x1b.orisun.GetUserCountRequest\x1a\x1c.orisun.GetUserCountResponse\x12L\n" +
	"\rGetEventCount\x12\x1c.orisun.GetEventCountRequest\x1a\x1d.orisun.GetEventCountResponseB?\n" +
	"\x10com.orisun.adminZ+github.com/OrisunLabs/Orisun/orisun/grpcapib\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_admin_proto_goTypes = []any{
	(BoundaryLifecycleStatus)(0),        // 0: orisun.BoundaryLifecycleStatus
	(*AdminUser)(nil),                   // 1: orisun.AdminUser
	(*CreateUserRequest)(nil),           // 2: orisun.CreateUserRequest
	(*CreateUserResponse)(nil),          // 3: orisun.CreateUserResponse
	(*DeleteUserRequest)(nil),           // 4: orisun.DeleteUserRequest
	(*DeleteUserResponse)(nil),          // 5: orisun.DeleteUserResponse
	(*ChangePasswordRequest)(nil),       // 6: orisun.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),      // 7: orisun.ChangePasswordResponse
	(*ListUsersRequest)(nil),            // 8: orisun.ListUsersRequest
	(*ListUsersResponse)(nil),           // 9: orisun.ListUsersResponse
	(*ValidateCredentialsRequest)(nil),  // 10: orisun.ValidateCredentialsRequest
	(*ValidateCredentialsResponse)(nil), // 11: orisun.ValidateCredentialsResponse
	(*GetUserCountRequest)(nil),         // 12: orisun.GetUserCountRequest
	(*GetUserCountResponse)(nil),        // 13: orisun.GetUserCountResponse
	(*GetEventCountRequest)(nil),        // 14: orisun.GetEventCountRequest
	(*GetEventCountResponse)(nil),       // 15: orisun.GetEventCountResponse
	(*BoundaryPlacementInput)(nil),      // 16: orisun.BoundaryPlacementInput
	(*BoundaryInfo)(nil),                // 17: orisun.BoundaryInfo
	(*CreateBoundaryRequest)(nil),       // 18: orisun.CreateBoundaryRequest
	(*CreateBoundaryResponse)(nil),      // 19: orisun.CreateBoundaryResponse
	(*ListBoundariesRequest)(nil),       // 20: orisun.ListBoundariesRequest
	(*ListBoundariesResponse)(nil),      // 21: orisun.ListBoundariesResponse
	(*GetBoundaryRequest)(nil),          // 22: orisun.GetBoundaryRequest
	(*GetBoundaryResponse)(nil),         // 23: orisun.GetBoundaryResponse
	(*timestamppb.Timestamp)(nil),       // 24: google.protobuf.Timestamp
	(*Position)(nil),                    // 25: orisun.Position
}
var file_admin_proto_depIdxs = []int32{
	24, // 0: orisun.AdminUser.created_at:type_name -> google.protobuf.Timestamp
	24, // 1: orisun.AdminUser.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: orisun.CreateUserResponse.user:type_name -> orisun.AdminUser
	1,  // 3: orisun.ListUsersResponse.users:type_name -> orisun.AdminUser
	1,  // 4: orisun.ValidateCredentialsResponse.user:type_name -> orisun.AdminUser
	16, // 5: orisun.BoundaryInfo.placement:type_name -> orisun.BoundaryPlacementInput
	0,  // 6: orisun.BoundaryInfo.status:type_name -> orisun.BoundaryLifecycleStatus
	25, // 7: orisun.BoundaryInfo.definition_position:type_name -> orisun.Position
	25, // 8: orisun.BoundaryInfo.status_position:type_name -> orisun.Position
	16, // 9: orisun.CreateBoundaryRequest.placement:type_name -> orisun.BoundaryPlacementInput
	17, // 10: orisun.CreateBoundaryResponse.boundary:type_name -> orisun.BoundaryInfo
	17, // 11: orisun.ListBoundariesResponse.boundaries:type_name -> orisun.BoundaryInfo
	17, // 12: orisun.GetBoundaryResponse.boundary:type_name -> orisun.BoundaryInfo
	18, // 13: orisun.Admin.CreateBoundary:input_type -> orisun.CreateBoundaryRequest
	20, // 14: orisun.Admin.ListBoundaries:input_type -> orisun.ListBoundariesRequest
	22, // 15: orisun.Admin.GetBoundary:input_type -> orisun.GetBoundaryRequest
	2,  // 16: orisun.Admin.CreateUser:input_type -> orisun.CreateUserRequest
	4,  // 17: orisun.Admin.DeleteUser:input_type -> orisun.DeleteUserRequest
	6,  // 18: orisun.Admin.ChangePassword:input_type -> orisun.ChangePasswordRequest
	8,  // 19: orisun.Admin.ListUsers:input_type -> orisun.ListUsersRequest
	10, // 20: orisun.Admin.ValidateCredentials:input_type -> orisun.ValidateCredentialsRequest
	12, // 21: orisun.Admin.GetUserCount:input_type -> orisun.GetUserCountRequest
	14, // 22: orisun.Admin.GetEventCount:input_type -> orisun.GetEventCountRequest
	19, // 23: orisun.Admin.CreateBoundary:output_type -> orisun.CreateBoundaryResponse
	21, // 24: orisun.Admin.ListBoundaries:output_type -> orisun.ListBoundariesResponse
	23, // 25: orisun.Admin.GetBoundary:output_type -> orisun.GetBoundaryResponse
	3,  // 26: orisun.Admin.CreateUser:output_type -> orisun.CreateUserResponse
	5,  // 27: orisun.Admin.DeleteUser:output_type -> orisun.DeleteUserResponse
	7,  // 28: orisun.Admin.ChangePassword:output_type -> orisun.ChangePasswordResponse
	9,  // 29: orisun.Admin.ListUsers:output_type -> orisun.ListUsersResponse
	11, // 30: orisun.Admin.ValidateCredentials:output_type -> orisun.ValidateCredentialsResponse
	13, // 31: orisun.Admin.GetUserCount:output_type -> orisun.GetUserCountResponse
	15, // 32: orisun.Admin.GetEventCount:output_type -> orisun.GetEventCountResponse
	23, // [23:33] is the sub-list for method output_type
	13, // [13:23] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	file_eventstore_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		EnumInfos:         file_admin_proto_enumTypes,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
