postgres:
  user: ${ORISUN_PG_USER:postgres}
  name: ${ORISUN_PG_NAME:orisun}
  password: ${ORISUN_PG_PASSWORD:password@1}
  host: ${ORISUN_PG_HOST:localhost}
  port: ${ORISUN_PG_PORT:5432}
  schemas: ${ORISUN_PG_SCHEMAS:`orisun_test_1:public,orisun_test_2:test2`}

boundaries:
  - name: orisun_test_1
    description: boundary1
  - name: orisun_test_2
    description: boundary2

grpc:
  port: ${ORISUN_GRPC_PORT:5005}
  enableReflection: ${ORISUN_GRPC_ENABLE_REFLECTION:true}
nats:
  serverName: ${ORISUN_NATS_SERVER_NAME:orisun-nats-2}
  port: ${ORISUN_NATS_PORT:4224}
  maxPayload: ${ORISUN_NATS_MAX_PAYLOAD:1048576}
  storeDir: ${ORISUN_NATS_STORE_DIR:../data/orisun}
  cluster:
    name: ${ORISUN_NATS_CLUSTER_NAME:orisun-nats-cluster}
    host: ${ORISUN_NATS_CLUSTER_HOST:0.0.0.0}
    port: ${ORISUN_NATS_CLUSTER_PORT:6222}
    username: ${ORISUN_NATS_CLUSTER_USERNAME:nats}
    password: ${ORISUN_NATS_CLUSTER_PASSWORD:password@1}
    enabled: ${ORISUN_NATS_CLUSTER_ENABLED:false}
    timeout: ${ORISUN_NATS_CLUSTER_TIMEOUT:1800s}
    routes: ${ORISUN_NATS_CLUSTER_ROUTES:`nats://0.0.0.0:6223,nats://0.0.0.0:6224`}
pollingPublisher:
  batchSize: ${ORISUN_POLLING_PUBLISHER_BATCH_SIZE:1000}
logging:
  level: ${ORISUN_LOGGING_LEVEL:DEBUG}

# authentication configuration
auth:
  adminUsername: ${ORISUN_ADMIN_USERNAME:admin}
  adminPassword: ${ORISUN_ADMIN_PASSWORD:changeit}

# Add to existing config:
admin:
  port: ${ORISUN_ADMIN_PORT:8991}
  schema: ${ORISUN_ADMIN_SCHEMA:public}
  boundary: ${ORISUN_ADMIN_BOUNDARY:orisun_test_2}