CREATE TABLE IF NOT EXISTS users_count (
    id VARCHAR(255) PRIMARY KEY,
    user_count VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);