// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: eventstore/eventstore.proto

package eventstore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_ASC  Direction = 0
	Direction_DESC Direction = 1
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	Direction_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_eventstore_eventstore_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_eventstore_eventstore_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_eventstore_eventstore_proto_rawDescGZIP(), []int{0}
}

type Position struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommitPosition  int64                  `protobuf:"varint,1,opt,name=commit_position,json=commitPosition,proto3" json:"commit_position,omitempty"`
	PreparePosition int64                  `protobuf:"varint,2,opt,name=prepare_position,json=preparePosition,proto3" json:"prepare_position,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_eventstore_eventstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_eventstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_eventstore_eventstore_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetCommitPosition() int64 {
	if x != nil {
		return x.CommitPosition
	}
	return 0
}

func (x *Position) GetPreparePosition() int64 {
	if x != nil {
		return x.PreparePosition
	}
	return 0
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_eventstore_eventstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_eventstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_eventstore_eventstore_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Criterion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Criterion) Reset() {
	*x = Criterion{}
	mi := &file_eventstore_eventstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Criterion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Criterion) ProtoMessage() {}

func (x *Criterion) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_eventstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Criterion.ProtoReflect.Descriptor instead.
func (*Criterion) Descriptor() ([]byte, []int) {
	return file_eventstore_eventstore_proto_rawDescGZIP(), []int{2}
}

func (x *Criterion) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Criteria      []*Criterion           `protobuf:"bytes,1,rep,name=criteria,proto3" json:"criteria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_eventstore_eventstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_eventstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_eventstore_eventstore_proto_rawDescGZIP(), []int{3}
}

func (x *Query) GetCriteria() []*Criterion {
	if x != nil {
		return x.Criteria
	}
	return nil
}

type EventToSave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventToSave) Reset() {
	*x = EventToSave{}
	mi := &file_eventstore_eventstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventToSave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventToSave) ProtoMessage() {}

func (x *EventToSave) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_eventstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventToSave.ProtoReflect.Descriptor instead.
func (*EventToSave) Descriptor() ([]byte, []int) {
	return file_eventstore_eventstore_proto_rawDescGZIP(), []int{4}
}

func (x *EventToSave) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventToSave) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventToSave) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *EventToSave) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Position      *Position              `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`
	DateCreated   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=date_created,json=dateCreated,proto3" json:"date_created,omitempty"`
	StreamId      string                 `protobuf:"bytes,8,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_eventstore_eventstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_eventstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_eventstore_eventstore_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Event) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Event) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Event) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.DateCreated
	}
	return nil
}

func (x *Event) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type WriteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogPosition   *Position              `protobuf:"bytes,1,opt,name=log_position,json=logPosition,proto3" json:"log_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResult) Reset() {
	*x = WriteResult{}
	mi := &file_eventstore_eventstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResult) ProtoMessage() {}

func (x *WriteResult) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_eventstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResult.ProtoReflect.Descriptor instead.
func (*WriteResult) Descriptor() ([]byte, []int) {
	return file_eventstore_eventstore_proto_rawDescGZIP(), []int{6}
}

func (x *WriteResult) GetLogPosition() *Position {
	if x != nil {
		return x.LogPosition
	}
	return nil
}

type SaveStreamQuery struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExpectedPosition *Position              `protobuf:"bytes,2,opt,name=expected_position,json=expectedPosition,proto3" json:"expected_position,omitempty"`
	SubsetQuery      *Query                 `protobuf:"bytes,3,opt,name=subsetQuery,proto3" json:"subsetQuery,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SaveStreamQuery) Reset() {
	*x = SaveStreamQuery{}
	mi := &file_eventstore_eventstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveStreamQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveStreamQuery) ProtoMessage() {}

func (x *SaveStreamQuery) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_eventstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveStreamQuery.ProtoReflect.Descriptor instead.
func (*SaveStreamQuery) Descriptor() ([]byte, []int) {
	return file_eventstore_eventstore_proto_rawDescGZIP(), []int{7}
}

func (x *SaveStreamQuery) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveStreamQuery) GetExpectedPosition() *Position {
	if x != nil {
		return x.ExpectedPosition
	}
	return nil
}

func (x *SaveStreamQuery) GetSubsetQuery() *Query {
	if x != nil {
		return x.SubsetQuery
	}
	return nil
}

type SaveEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boundary      string                 `protobuf:"bytes,2,opt,name=boundary,proto3" json:"boundary,omitempty"`
	Stream        *SaveStreamQuery       `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"`
	Events        []*EventToSave         `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveEventsRequest) Reset() {
	*x = SaveEventsRequest{}
	mi := &file_eventstore_eventstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveEventsRequest) ProtoMessage() {}

func (x *SaveEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_eventstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveEventsRequest.ProtoReflect.Descriptor instead.
func (*SaveEventsRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_eventstore_proto_rawDescGZIP(), []int{8}
}

func (x *SaveEventsRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

func (x *SaveEventsRequest) GetStream() *SaveStreamQuery {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *SaveEventsRequest) GetEvents() []*EventToSave {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetStreamQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FromPosition  *Position              `protobuf:"bytes,2,opt,name=from_position,json=fromPosition,proto3" json:"from_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamQuery) Reset() {
	*x = GetStreamQuery{}
	mi := &file_eventstore_eventstore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamQuery) ProtoMessage() {}

func (x *GetStreamQuery) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_eventstore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamQuery.ProtoReflect.Descriptor instead.
func (*GetStreamQuery) Descriptor() ([]byte, []int) {
	return file_eventstore_eventstore_proto_rawDescGZIP(), []int{9}
}

func (x *GetStreamQuery) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetStreamQuery) GetFromPosition() *Position {
	if x != nil {
		return x.FromPosition
	}
	return nil
}

type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *Query                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	FromPosition  *Position              `protobuf:"bytes,2,opt,name=from_position,json=fromPosition,proto3" json:"from_position,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Direction     Direction              `protobuf:"varint,4,opt,name=direction,proto3,enum=eventstore.Direction" json:"direction,omitempty"`
	Boundary      string                 `protobuf:"bytes,5,opt,name=boundary,proto3" json:"boundary,omitempty"`
	Stream        *GetStreamQuery        `protobuf:"bytes,6,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_eventstore_eventstore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_eventstore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_eventstore_proto_rawDescGZIP(), []int{10}
}

func (x *GetEventsRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *GetEventsRequest) GetFromPosition() *Position {
	if x != nil {
		return x.FromPosition
	}
	return nil
}

func (x *GetEventsRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetEventsRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_ASC
}

func (x *GetEventsRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

func (x *GetEventsRequest) GetStream() *GetStreamQuery {
	if x != nil {
		return x.Stream
	}
	return nil
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_eventstore_eventstore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_eventstore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_eventstore_eventstore_proto_rawDescGZIP(), []int{11}
}

func (x *GetEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type CatchUpSubscribeToEventStoreRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AfterPosition  *Position              `protobuf:"bytes,1,opt,name=afterPosition,proto3" json:"afterPosition,omitempty"`
	Query          *Query                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	SubscriberName string                 `protobuf:"bytes,3,opt,name=subscriber_name,json=subscriberName,proto3" json:"subscriber_name,omitempty"`
	Boundary       string                 `protobuf:"bytes,4,opt,name=boundary,proto3" json:"boundary,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CatchUpSubscribeToEventStoreRequest) Reset() {
	*x = CatchUpSubscribeToEventStoreRequest{}
	mi := &file_eventstore_eventstore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchUpSubscribeToEventStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchUpSubscribeToEventStoreRequest) ProtoMessage() {}

func (x *CatchUpSubscribeToEventStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_eventstore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchUpSubscribeToEventStoreRequest.ProtoReflect.Descriptor instead.
func (*CatchUpSubscribeToEventStoreRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_eventstore_proto_rawDescGZIP(), []int{12}
}

func (x *CatchUpSubscribeToEventStoreRequest) GetAfterPosition() *Position {
	if x != nil {
		return x.AfterPosition
	}
	return nil
}

func (x *CatchUpSubscribeToEventStoreRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *CatchUpSubscribeToEventStoreRequest) GetSubscriberName() string {
	if x != nil {
		return x.SubscriberName
	}
	return ""
}

func (x *CatchUpSubscribeToEventStoreRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

type CatchUpSubscribeToStreamRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Query          *Query                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	SubscriberName string                 `protobuf:"bytes,3,opt,name=subscriber_name,json=subscriberName,proto3" json:"subscriber_name,omitempty"`
	Boundary       string                 `protobuf:"bytes,4,opt,name=boundary,proto3" json:"boundary,omitempty"`
	Stream         string                 `protobuf:"bytes,5,opt,name=stream,proto3" json:"stream,omitempty"`
	AfterPosition  *Position              `protobuf:"bytes,6,opt,name=after_position,json=afterPosition,proto3" json:"after_position,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CatchUpSubscribeToStreamRequest) Reset() {
	*x = CatchUpSubscribeToStreamRequest{}
	mi := &file_eventstore_eventstore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchUpSubscribeToStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchUpSubscribeToStreamRequest) ProtoMessage() {}

func (x *CatchUpSubscribeToStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventstore_eventstore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchUpSubscribeToStreamRequest.ProtoReflect.Descriptor instead.
func (*CatchUpSubscribeToStreamRequest) Descriptor() ([]byte, []int) {
	return file_eventstore_eventstore_proto_rawDescGZIP(), []int{13}
}

func (x *CatchUpSubscribeToStreamRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *CatchUpSubscribeToStreamRequest) GetSubscriberName() string {
	if x != nil {
		return x.SubscriberName
	}
	return ""
}

func (x *CatchUpSubscribeToStreamRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

func (x *CatchUpSubscribeToStreamRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *CatchUpSubscribeToStreamRequest) GetAfterPosition() *Position {
	if x != nil {
		return x.AfterPosition
	}
	return nil
}

var File_eventstore_eventstore_proto protoreflect.FileDescriptor

const file_eventstore_eventstore_proto_rawDesc = "" +
	"\n" +
	"\x1beventstore/eventstore.proto\x12\n" +
	"eventstore\x1a\x1fgoogle/protobuf/timestamp.proto\"^\n" +
	"\bPosition\x12'\n" +
	"\x0fcommit_position\x18\x01 \x01(\x03R\x0ecommitPosition\x12)\n" +
	"\x10prepare_position\x18\x02 \x01(\x03R\x0fpreparePosition\"-\n" +
	"\x03Tag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"0\n" +
	"\tCriterion\x12#\n" +
	"\x04tags\x18\x01 \x03(\v2\x0f.eventstore.TagR\x04tags\":\n" +
	"\x05Query\x121\n" +
	"\bcriteria\x18\x01 \x03(\v2\x15.eventstore.CriterionR\bcriteria\"w\n" +
	"\vEventToSave\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\"\xff\x01\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\x120\n" +
	"\bposition\x18\x06 \x01(\v2\x14.eventstore.PositionR\bposition\x12=\n" +
	"\fdate_created\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\x12\x1b\n" +
	"\tstream_id\x18\b \x01(\tR\bstreamId\"F\n" +
	"\vWriteResult\x127\n" +
	"\flog_position\x18\x01 \x01(\v2\x14.eventstore.PositionR\vlogPosition\"\x9d\x01\n" +
	"\x0fSaveStreamQuery\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12A\n" +
	"\x11expected_position\x18\x02 \x01(\v2\x14.eventstore.PositionR\x10expectedPosition\x123\n" +
	"\vsubsetQuery\x18\x03 \x01(\v2\x11.eventstore.QueryR\vsubsetQuery\"\x95\x01\n" +
	"\x11SaveEventsRequest\x12\x1a\n" +
	"\bboundary\x18\x02 \x01(\tR\bboundary\x123\n" +
	"\x06stream\x18\x03 \x01(\v2\x1b.eventstore.SaveStreamQueryR\x06stream\x12/\n" +
	"\x06events\x18\x04 \x03(\v2\x17.eventstore.EventToSaveR\x06events\"_\n" +
	"\x0eGetStreamQuery\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\rfrom_position\x18\x02 \x01(\v2\x14.eventstore.PositionR\ffromPosition\"\x91\x02\n" +
	"\x10GetEventsRequest\x12'\n" +
	"\x05query\x18\x01 \x01(\v2\x11.eventstore.QueryR\x05query\x129\n" +
	"\rfrom_position\x18\x02 \x01(\v2\x14.eventstore.PositionR\ffromPosition\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x123\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x15.eventstore.DirectionR\tdirection\x12\x1a\n" +
	"\bboundary\x18\x05 \x01(\tR\bboundary\x122\n" +
	"\x06stream\x18\x06 \x01(\v2\x1a.eventstore.GetStreamQueryR\x06stream\">\n" +
	"\x11GetEventsResponse\x12)\n" +
	"\x06events\x18\x01 \x03(\v2\x11.eventstore.EventR\x06events\"\xcf\x01\n" +
	"#CatchUpSubscribeToEventStoreRequest\x12:\n" +
	"\rafterPosition\x18\x01 \x01(\v2\x14.eventstore.PositionR\rafterPosition\x12'\n" +
	"\x05query\x18\x02 \x01(\v2\x11.eventstore.QueryR\x05query\x12'\n" +
	"\x0fsubscriber_name\x18\x03 \x01(\tR\x0esubscriberName\x12\x1a\n" +
	"\bboundary\x18\x04 \x01(\tR\bboundary\"\xe4\x01\n" +
	"\x1fCatchUpSubscribeToStreamRequest\x12'\n" +
	"\x05query\x18\x02 \x01(\v2\x11.eventstore.QueryR\x05query\x12'\n" +
	"\x0fsubscriber_name\x18\x03 \x01(\tR\x0esubscriberName\x12\x1a\n" +
	"\bboundary\x18\x04 \x01(\tR\bboundary\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\tR\x06stream\x12;\n" +
	"\x0eafter_position\x18\x06 \x01(\v2\x14.eventstore.PositionR\rafterPosition*\x1e\n" +
	"\tDirection\x12\a\n" +
	"\x03ASC\x10\x00\x12\b\n" +
	"\x04DESC\x10\x012\xe4\x02\n" +
	"\n" +
	"EventStore\x12F\n" +
	"\n" +
	"SaveEvents\x12\x1d.eventstore.SaveEventsRequest\x1a\x17.eventstore.WriteResult\"\x00\x12J\n" +
	"\tGetEvents\x12\x1c.eventstore.GetEventsRequest\x1a\x1d.eventstore.GetEventsResponse\"\x00\x12b\n" +
	"\x18CatchUpSubscribeToEvents\x12/.eventstore.CatchUpSubscribeToEventStoreRequest\x1a\x11.eventstore.Event\"\x000\x01\x12^\n" +
	"\x18CatchUpSubscribeToStream\x12+.eventstore.CatchUpSubscribeToStreamRequest\x1a\x11.eventstore.Event\"\x000\x01B*\n" +
	"\x15com.orisun.eventstoreZ\x11orisun/eventstoreb\x06proto3"

var (
	file_eventstore_eventstore_proto_rawDescOnce sync.Once
	file_eventstore_eventstore_proto_rawDescData []byte
)

func file_eventstore_eventstore_proto_rawDescGZIP() []byte {
	file_eventstore_eventstore_proto_rawDescOnce.Do(func() {
		file_eventstore_eventstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eventstore_eventstore_proto_rawDesc), len(file_eventstore_eventstore_proto_rawDesc)))
	})
	return file_eventstore_eventstore_proto_rawDescData
}

var file_eventstore_eventstore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_eventstore_eventstore_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_eventstore_eventstore_proto_goTypes = []any{
	(Direction)(0),                              // 0: eventstore.Direction
	(*Position)(nil),                            // 1: eventstore.Position
	(*Tag)(nil),                                 // 2: eventstore.Tag
	(*Criterion)(nil),                           // 3: eventstore.Criterion
	(*Query)(nil),                               // 4: eventstore.Query
	(*EventToSave)(nil),                         // 5: eventstore.EventToSave
	(*Event)(nil),                               // 6: eventstore.Event
	(*WriteResult)(nil),                         // 7: eventstore.WriteResult
	(*SaveStreamQuery)(nil),                     // 8: eventstore.SaveStreamQuery
	(*SaveEventsRequest)(nil),                   // 9: eventstore.SaveEventsRequest
	(*GetStreamQuery)(nil),                      // 10: eventstore.GetStreamQuery
	(*GetEventsRequest)(nil),                    // 11: eventstore.GetEventsRequest
	(*GetEventsResponse)(nil),                   // 12: eventstore.GetEventsResponse
	(*CatchUpSubscribeToEventStoreRequest)(nil), // 13: eventstore.CatchUpSubscribeToEventStoreRequest
	(*CatchUpSubscribeToStreamRequest)(nil),     // 14: eventstore.CatchUpSubscribeToStreamRequest
	(*timestamppb.Timestamp)(nil),               // 15: google.protobuf.Timestamp
}
var file_eventstore_eventstore_proto_depIdxs = []int32{
	2,  // 0: eventstore.Criterion.tags:type_name -> eventstore.Tag
	3,  // 1: eventstore.Query.criteria:type_name -> eventstore.Criterion
	1,  // 2: eventstore.Event.position:type_name -> eventstore.Position
	15, // 3: eventstore.Event.date_created:type_name -> google.protobuf.Timestamp
	1,  // 4: eventstore.WriteResult.log_position:type_name -> eventstore.Position
	1,  // 5: eventstore.SaveStreamQuery.expected_position:type_name -> eventstore.Position
	4,  // 6: eventstore.SaveStreamQuery.subsetQuery:type_name -> eventstore.Query
	8,  // 7: eventstore.SaveEventsRequest.stream:type_name -> eventstore.SaveStreamQuery
	5,  // 8: eventstore.SaveEventsRequest.events:type_name -> eventstore.EventToSave
	1,  // 9: eventstore.GetStreamQuery.from_position:type_name -> eventstore.Position
	4,  // 10: eventstore.GetEventsRequest.query:type_name -> eventstore.Query
	1,  // 11: eventstore.GetEventsRequest.from_position:type_name -> eventstore.Position
	0,  // 12: eventstore.GetEventsRequest.direction:type_name -> eventstore.Direction
	10, // 13: eventstore.GetEventsRequest.stream:type_name -> eventstore.GetStreamQuery
	6,  // 14: eventstore.GetEventsResponse.events:type_name -> eventstore.Event
	1,  // 15: eventstore.CatchUpSubscribeToEventStoreRequest.afterPosition:type_name -> eventstore.Position
	4,  // 16: eventstore.CatchUpSubscribeToEventStoreRequest.query:type_name -> eventstore.Query
	4,  // 17: eventstore.CatchUpSubscribeToStreamRequest.query:type_name -> eventstore.Query
	1,  // 18: eventstore.CatchUpSubscribeToStreamRequest.after_position:type_name -> eventstore.Position
	9,  // 19: eventstore.EventStore.SaveEvents:input_type -> eventstore.SaveEventsRequest
	11, // 20: eventstore.EventStore.GetEvents:input_type -> eventstore.GetEventsRequest
	13, // 21: eventstore.EventStore.CatchUpSubscribeToEvents:input_type -> eventstore.CatchUpSubscribeToEventStoreRequest
	14, // 22: eventstore.EventStore.CatchUpSubscribeToStream:input_type -> eventstore.CatchUpSubscribeToStreamRequest
	7,  // 23: eventstore.EventStore.SaveEvents:output_type -> eventstore.WriteResult
	12, // 24: eventstore.EventStore.GetEvents:output_type -> eventstore.GetEventsResponse
	6,  // 25: eventstore.EventStore.CatchUpSubscribeToEvents:output_type -> eventstore.Event
	6,  // 26: eventstore.EventStore.CatchUpSubscribeToStream:output_type -> eventstore.Event
	23, // [23:27] is the sub-list for method output_type
	19, // [19:23] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_eventstore_eventstore_proto_init() }
func file_eventstore_eventstore_proto_init() {
	if File_eventstore_eventstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eventstore_eventstore_proto_rawDesc), len(file_eventstore_eventstore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eventstore_eventstore_proto_goTypes,
		DependencyIndexes: file_eventstore_eventstore_proto_depIdxs,
		EnumInfos:         file_eventstore_eventstore_proto_enumTypes,
		MessageInfos:      file_eventstore_eventstore_proto_msgTypes,
	}.Build()
	File_eventstore_eventstore_proto = out.File
	file_eventstore_eventstore_proto_goTypes = nil
	file_eventstore_eventstore_proto_depIdxs = nil
}
