// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package changepassword

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ChangePasswordDialog() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<sl-dialog id=\"change-password-dialog\" label=\"Change Password\" class=\"dialog-overview\" data-signals=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(`{currentPassword: '', newPassword: '', confirmPassword: '' , message: '' , success: '' , failed: '' }`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `admin/slices/change_password/change_password.templ`, Line: 8, Col: 120}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><form method=\"post\" action=\"/change-password\" data-on-submit=\"@post(&#39;/change-password&#39;)\"><div class=\"space-y-4\"><sl-input type=\"password\" label=\"Current Password\" data-on-sl-input__case.kebab=\"$currentPassword = evt.target.value\" pill required clearable password-toggle><sl-icon slot=\"prefix\" name=\"key\"></sl-icon></sl-input> <sl-input type=\"password\" label=\"New Password\" data-on-sl-input__case.kebab=\"$newPassword = evt.target.value\" pill required clearable password-toggle><sl-icon slot=\"prefix\" name=\"key\"></sl-icon></sl-input> <sl-input type=\"password\" label=\"Confirm New Password\" data-on-sl-input__case.kebab=\"$confirmPassword = evt.target.value\" pill required clearable password-toggle><sl-icon slot=\"prefix\" name=\"key\"></sl-icon></sl-input></div><div class=\"gap-3\"></div><div slot=\"footer\" class=\"flex justify-end mt-4 gap-3\"><sl-button pill data-on-click=\"document.querySelector(&#39;#change-password-dialog&#39;).hide()\"><sl-icon slot=\"prefix\" name=\"x-circle\"></sl-icon> Cancel</sl-button> <sl-button pill variant=\"primary\" type=\"submit\"><sl-icon slot=\"prefix\" name=\"check2-circle\"></sl-icon> Change Password</sl-button></div></form></sl-dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
